#!/usr/bin/env fish

# Abort commit with untracked files

make deps > /dev/null

if test $status != 0
	echo "Build failed! Can't commit"
	exit 1
end

set -l result 0

for file in (cat build/Kernel.d | string split ' ' | uniq | grep -v compiler)
	git check-ignore $file

	if test $status = 0
		continue
	end

	git ls-files --error-unmatch $file 2&> /dev/null
	
	if test $status = 1
		echo (string replace "$(pwd)" '.' $file)' is not tracked!' >&2
		set result 1
	end
end

exit $result