#!/usr/bin/env fish

# Abort commit with untracked files

set -l result 0

for file in (cat build/Kernel.d | string split ' ' | uniq | grep -v compiler)
	git ls-files --error-unmatch $file 2&> /dev/null
	
	if test $status = 1
		echo (string replace "$(pwd)" '.' $file)' is not tracked!' >&2
		set result 1
	end
end

exit $result