qemu-system-x86_64 \
	-accel tcg,thread=single \
	-cpu core2duo \
	-m 128 \
	-no-reboot \
	-drive index=0,format=raw,media=disk,file=./build/disk.img \
	-serial stdio \
	-smp 1 \
	-usb \
	-vga std \
	-s